project:
  type: book

book:
  title: "Examples in Time Series Analysis and Application"
  author: "Youngrok Lee"
  date: "7/2/2024"
  chapters:
    - index.qmd
    - ch01_smoothing.qmd
    - ch02_stationary.qmd
  repo-url: https://github.com/youngroklee-ml/time-series-book-examples

format:
  html:
    theme: cosmo



